name: Deploy on dev
on:
 push:
  branches: [ main ]

jobs:
 redeploy:
   runs-on: ubuntu-latest
   steps: 
    - run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
        echo "${{ secrets.KNOWN_HOSTS }}" &> ~/.ssh/known_hosts
        mkdir .ssh
        ssh -i ~/ssh_key root@3.110.114.166
        cd Turbo-Deployment/ && git pull
        pnpm install
        pnpm run build
        pm2 restart http-server
        pm2 restart ws-server
        pm2 restart web