name: Deploy on dev
on:
 push:
  branches: [ main ]

jobs:
 uses: ubuntu-latest
 redeploy:
   runs-on: Deploying everything to the dev cluster

   steps: 
    - run: |
        echo ${{ secrets.SSH_PRIVATE_KEY }} &> ~/ssh_key
        ssh -i ~/ssh_key root@3.110.114.166
        cd Turbo-Deployment/ && git pull
        pnpm install
        pnpm run build
        pm2 restart http-server
        pm2 restart ws-server
        pm2 restart web