name: Deploy on dev
on:
 push:
  branches: [ main ]

jobs:
 redeploy:
   runs-on: ubuntu-latest
   steps: 
    - run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
        mkdir -p /home/runner/.ssh
        touch /home/runner/.ssh/known_hosts
        echo "previous step"
        echo "${{ secrets.KNOWN_HOSTS }}" &> ~/.ssh/known_hosts
        echo "next step"
        ls -la ~/.ssh/
        chmod 700 /home/runner/ssh_key
        ssh -i ~/ssh_key root@3.110.114.166 -t "cd Turbo-Deployment/ && git pull && pnpm install && pnpm run build && pm2 restart http-server && pm2 restart ws-server && pm2 restart web"